# Generated by Django 5.2.6 on 2025-09-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('active_wear', 'Active Wear'), ('footwear', 'Footwear'), ('equipments', 'Equipments'), ('nutrition_supplement', 'Nutrition & Supplement'), ('accessories', 'Accessories'), ('exclusive', 'Exclusive Items')], default='update', max_length=100)),
                ('product_views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
