# Generated by Django 5.2.8 on 2025-11-15 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('active_wear', 'Active Wear'), ('footwear', 'Footwear'), ('equipments', 'Equipments'), ('nutrition_supplement', 'Nutrition & Supplement'), ('accessories', 'Accessories'), ('exclusive', 'Exclusive Items')], default='apparel', max_length=100),
        ),
    ]
