# Generated by Django 5.2.6 on 2025-09-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('active_wear', 'Active Wear'), ('footwear', 'Footwear'), ('equipments', 'Equipments'), ('nutrition_supplement', 'Nutrition & Supplement'), ('accessories', 'Accessories'), ('exclusive', 'Exclusive Items')], default='update', max_length=100),
        ),
    ]
